### ISSUE TITLE
2个问题

### ISSUE THREAD

**Issue by Fengzhijjin** [kwai/DouZero#10]
1. 第一局我选择了地主上家角色，我的队友地主下家从头到尾就出了一张牌，然后地主赢，在现实中基本很难打成这样吧。
2. 第二局我选择了地主角色，然后我居然赢了

**Comment by Fengzhijjin** [comment]
等待官方啥时候组织场跟职业选手对战比赛，倒是职业选手被虐，我又赢了DouZero，哈哈哈哈！

**Comment by daochenzha** [comment]
@Fengzhijjin 斗地主不像围棋，随机性比较大，不可能做到100%赢。所以我们优化的是总体的胜率。确实有些时候会有些奇怪的操作，但这都是算法自己打自己学出来，我们也无法解释。总体上，我们对一般人类还是能达到60%胜率的。

**Comment by Fengzhijjin** [comment]
@daochenzha   嗯嗯。 确实因为发牌原因，天然的会造成胜率的差距。
