### ISSUE TITLE
关于算法

### ISSUE THREAD

**Issue by budaLi** [kwai/DouZero#13]
感觉目前开发的算法是基于三方都明牌的情况下开发的，并不能像黑盒一样辅助人或者自己去完成斗地主游戏

**Comment by daochenzha** [comment]
目前的算法是暗牌的，在demo中加了上帝视角是为了让玩家方便看，但对AI是隐藏的。

**Comment by geekli** [comment]
@daochenzha 但是打了几场 比如我是地主，看对方两个农民的出牌策略感觉是知道是知道对方需要什么牌一样，经常出现喂牌的情况。而且感觉也能猜出来我的牌是什么。

**Comment by karoka** [comment]
@geekli 就像人类玩家一样，AI也可以一定程度上通过别人出过的牌来猜测别人的手牌。尤其是在游戏中后期，这个猜测可以非常准确，因此斗地主高手对局中往往需要进行“藏牌”的操作，以避免暴露自己的手牌。
