### ISSUE TITLE
请问基于强化学习？数据怎么得到？

### ISSUE THREAD

**Issue by henbucuoshanghai** [kwai/DouZero#16]
在出牌的时候，电脑会记牌？分析得到最好的策略？

**Comment by daochenzha** [comment]
@henbucuoshanghai 电脑能看到的包括自己的手牌、历史出牌记录等（但不包括其他玩家手牌）。具体用到的特征可参考代码，比如地主的特征在这里 https://github.com/kwai/DouZero/blob/main/douzero/env/env.py#L286-L372
