### ISSUE TITLE
Actions generate by model differ from online demo

### ISSUE THREAD

**Issue by boscotsang** [kwai/DouZero#19]
![image](https://user-images.githubusercontent.com/7187749/123387821-c4651100-d5ca-11eb-9f80-cdf412531091.png)

![image](https://user-images.githubusercontent.com/7187749/123387829-c62ed480-d5ca-11eb-9d74-aa7b433e584f.png)

As the pictures above, the peasant's action is "5777" in demo while "3777" in model and code provided in github.
The md5 of landlord model is `b3eaa5f6e146e34c1b9f8cc6c9e5522f  landlord.ckpt`

**Comment by daochenzha** [comment]
We have two pre-trained models, WP and ADP. The demo uses WP. Make sure they are the same.
