### ISSUE TITLE
为什么evaluate出错？

### ISSUE THREAD

**Issue by leolle** [kwai/DouZero#20]
前面已经产生了测试数据，但是在这一步
python evaluate.py --landlord random --landlord_up random --landlord_down random
发现在simulation.py 里面num_total_wins = 0
请问怎么回事？

**Comment by daochenzha** [comment]
@leolle 请问您用的是什么操作系统？Windows可能有这个问题。因为evaluation的时候用了多个进程，windows进程机制不一样，导致数据传输出了问题

**Comment by daochenzha** [comment]
现在的程序是通过共享主进程的变量来计数。这在Windows下可能不行。可能的解决方法是用队列实现进程通信。我手上没有windows机器，目前还没法尝试。希望谁有Windows机器的能试试看。

**Comment by leolle** [comment]
我是windows系统，改成1个worker吗？

**Comment by daochenzha** [comment]
@mookrs 代码更新了，现在改成用队列通信，window现在可以跑了吗？

**Comment by mookrs** [comment]
> @mookrs 代码更新了，现在改成用队列通信，window现在可以跑了吗？

cc @leolle , you cloud have a try.

**Comment by hsywhu** [comment]
I've tested the new code on PyTorch 1.9 CPU ver. with Windows, and can successfully run the evaluation
