### ISSUE TITLE
使用训练模型的过程中，会出现普通炸大于王炸的情况

### ISSUE THREAD

**Issue by jiugewx** [kwai/DouZero#26]
使用训练模型的过程中，会出现普通炸大于王炸的情况。这个是否会影响wp，adp等训练数据

**Comment by daochenzha** [comment]
@jiugewx 这个看起来不合理，可能是bug，可以说下具体什么情况下碰到的吗？

**Comment by jiugewx** [comment]
地主: DX222AAKQJJ99988765
下家：2KKQJTT8765444433
上家：AAKQQJTT987766553
出牌顺序：3,5,T,Q,K,,2,,,8,J,Q,K,,A,2,,,99,,,JJ,,,AA,,,56789,,89TJQ,DX
此时提示下家出 4444

**Comment by daochenzha** [comment]
@jiugewx 感谢反馈，这个的原因是，必须得用XD才行不能DX，训练时不会有这个问题，因为牌都是排号序的。我们会再检查下前端。

**Comment by daochenzha** [comment]
@jiugewx 我们又检查了一遍，demo是先排好序再请求的，所以应该没有问题。

**Comment by jiugewx** [comment]
@daochenzha  这个和前端无关，我是直接调用接口的，没有做排序处理。阅读了源码，知道问题产生的原因了。感谢回复
