### ISSUE TITLE
亲测，效果一般。对战水平低下，我这样一般人胜利都在50%以上

### ISSUE THREAD

**Issue by luyifanlu** [kwai/DouZero#3]
根本就没有zero的水平，假设要迭代10次，达到alpha zero ，现在还在第九代 。

**Comment by daochenzha** [comment]
感谢反馈，我们后台显示DouZero还是很强的，目前人类综合胜率不到40%，在斗地主这样随机性比较大的游戏算是还不错了。可能您是斗地主高手 :) 当然DouZero可能确实还有提升空间，就像您说的迭代第十次。我们会继续努力💪

**Comment by reminisences** [comment]
> 根本就没有zero的水平，假设要迭代10次，达到alpha zero ，现在还在第九代 。

你说反了,现在才是第一代而已吧, 假如迭代10次,达到alpha zero. 正如作者所言第一代人类胜率不足40%，第九代的alhpa zero 你能赢算我输！！！

**Comment by luyifanlu** [comment]
> > 根本就没有zero的水平，假设要迭代10次，达到alpha zero ，现在还在第九代 。
> 
> 你说反了,现在才是第一代而已吧, 假如迭代10次,达到alpha zero. 正如作者所言第一代人类胜率不足40%，第九代的alhpa zero 你能赢算我输！！！

请仔细阅读，多就不说了。
