### ISSUE TITLE
出牌未校验是否大过上家

### ISSUE THREAD

**Issue by changjiuxiong** [kwai/DouZero#34]
训练时没问题，手动改出牌时有这个问题。比如上家出5，我强制让地主出3，游戏没提示出错，而且下家还接着我出了4

**Comment by karoka** [comment]
如果AI出了不合法操作游戏环境应该会报错

**Comment by karoka** [comment]
I see. 这里确实没做校验
原本代码`action = self.players[self.acting_player_position].act(
            self.game_infoset)`中默认players action一定legal了。

可能还是加个assertion会比较好，我开了个PR #35
