### ISSUE TITLE
执行loss.backward()几个小时报错out of memory

### ISSUE THREAD

**Issue by SvenNJ** [kwai/DouZero#54]
应该出现了OOM，报错如下：
`
Exception in thread batch-and-learn-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zzy/robot/DouZeroV2/douzero/dmc/dmc.py", line 238, in batch_and_learn
    _stats = learn(position, models, learner_model.get_model(position), batch, optimizers[position], flags, position_lock)
  File "/home/zzy/robot/DouZeroV2/douzero/dmc/dmc.py", line 101, in learn
    loss.backward()
  File "/home/zzy/.local/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/zzy/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
`

显存 2G，CUDA Version: 11.7， 启动参数已经调的比较小了：
python3 train.py --gpu_devices 0 --load_model --batch_size 16 --num_actor_devices 1 --num_actors 1 --num_threads 1 --training_device 0

**Comment by daochenzha** [comment]
@SvenNJ 可能打牌过程中某一步legal action size太大了导致几个小时后崩。建议换个大点显存的GPU或者用CPU训练

**Comment by SvenNJ** [comment]
用CPU训练没问题，但是 CPU训练太慢了，我还有一台机器用的8 CPU， 同时跑，CPU这里平均 80fps， 另外一个机器用一个显卡 跑能跑到 平均900fps

**Comment by SvenNJ** [comment]
而且CPU这里 输出到 log.csv这里 打印的结果 速度 远比 用GPU这里的 慢， GPU这里 log.csv 输出的结果很快

**Comment by SvenNJ** [comment]
报错信息：
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 1.95 GiB total capacity; 180.87 MiB already allocated; 18.44 MiB free; 194.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by SvenNJ** [comment]
一般你们实验室 用的什么系统， 显卡配置大概是什么样子的， 可以发下 我参考下吗

**Comment by SvenNJ** [comment]
感觉有显存泄漏，跑一个小时观察了下，发现显存一直在增加，就没有降过，是不是你们显存比较大没有发现这个问题？2G显存 跑2个actor 快满了，然后报错：
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 1.95 GiB total capacity; 180.87 MiB already allocated; 18.44 MiB free; 194.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
