### ISSUE TITLE
关于深度学习与强化学习

### ISSUE THREAD

**Issue by Zz-Quan** [kwai/DouZero#64]
我看了下代码，捋了下逻辑大致如下（如有错误请指正）：
  构建斗地主规则环境->执行随机行为->记录本次特征数据及行为->对局结束，计算奖励->将数据list及奖励输入模型训练

在我看来，对局结束后，将数据以及奖励输入模型的行为与给数据打标签是等效的，这是否可以理解为深度学习？

比如，这样一种情况称为强化学习是否更加合适：
  构建斗地主规则环境->执行模型预测行为->记录本次特征数据及行为->对局结束，计算奖励->将数据list及奖励输入模型训练
但是这样与蒙特卡洛思想是冲突的。

**Comment by daochenzha** [comment]
@Zz-Quan 构建斗地主规则环境->执行模型预测行为->记录本次特征数据及行为->对局结束，计算奖励->将数据list及奖励输入模型训练 这种是对的。这是深度学习，更准确点是深度强化学习。

这个和蒙特卡洛思想不冲突，这里的随机是用当前的策略随机采样

**Comment by Zz-Quan** [comment]
多谢回复！想了想其实理论基础和思想最重要，不必纠结于各种概念:)
