### ISSUE TITLE
勾吧pretrain models都没有   一训练全是0

### ISSUE THREAD

**Issue by SchoolBug** [kwai/DouZero#68]
[INFO:7015 dmc:243 2023-05-27 00:06:24,911] After 0 (L:0 U:0 D:0) frames: @ 0.0 fps (avg@ 0.0 fps) (L:0.0 U:0.0 D:0.0) Stats:
{'loss_landlord': 0,
 'loss_landlord_down': 0,
 'loss_landlord_up': 0,
 'mean_episode_return_landlord': 0,
 'mean_episode_return_landlord_down': 0,
 'mean_episode_return_landlord_up': 0}

**Comment by lingyunQAQ** [comment]
解决了吗。。。。

**Comment by daochenzha** [comment]
@SchoolBug 能提供更多信息吗？比如用什么系统和GPU？
